--
DELETE FROM pwaf_app_admin.http_request_routes WHERE path = '/pwaf_app_admin';
INSERT INTO pwaf_app_admin.http_request_routes (id,path,controller,require_valid_user) VALUES (3001,'/pwaf_app_admin','pwaf_app_admin.pub_controller_main',True);

DELETE FROM pwaf_app_admin.http_request_routes WHERE path = '/pwaf_app_admin/editor';
INSERT INTO pwaf_app_admin.http_request_routes (id,path,controller,require_valid_user) VALUES (3002,'/pwaf_app_admin/editor','pwaf_app_admin.pub_controller_editor',True);
--

TRUNCATE pwaf_app_admin.assets CASCADE;
COPY pwaf_app_admin.assets (id, content_type, data, name) FROM stdin;
3003	text/javascript	// Set desired tab- defaults to four space softtab\r\nvar tab = "    ";\r\n       \r\nfunction checkTab(evt) {\r\n    var t = evt.target;\r\n    var ss = t.selectionStart;\r\n    var se = t.selectionEnd;\r\n \r\n    // Tab key - insert tab expansion\r\n    if (evt.keyCode == 9) {\r\n        evt.preventDefault();\r\n               \r\n        // Special case of multi line selection\r\n        if (ss != se && t.value.slice(ss,se).indexOf("n") != -1) {\r\n            // In case selection was not of entire lines (e.g. selection begins in the middle of a line)\r\n            // we ought to tab at the beginning as well as at the start of every following line.\r\n            var pre = t.value.slice(0,ss);\r\n            var sel = t.value.slice(ss,se).replace(/n/g,"n"+tab);\r\n            var post = t.value.slice(se,t.value.length);\r\n            t.value = pre.concat(tab).concat(sel).concat(post);\r\n                   \r\n            t.selectionStart = ss + tab.length;\r\n            t.selectionEnd = se + tab.length;\r\n        }\r\n               \r\n        // "Normal" case (no selection or selection on one line only)\r\n        else {\r\n            t.value = t.value.slice(0,ss).concat(tab).concat(t.value.slice(ss,t.value.length));\r\n            if (ss == se) {\r\n                t.selectionStart = t.selectionEnd = ss + tab.length;\r\n            }\r\n            else {\r\n                t.selectionStart = ss + tab.length;\r\n                t.selectionEnd = se + tab.length;\r\n            }\r\n        }\r\n    }\r\n           \r\n    // Backspace key - delete preceding tab expansion, if exists\r\n   else if (evt.keyCode==8 && t.value.slice(ss - 4,ss) == tab) {\r\n        evt.preventDefault();\r\n               \r\n        t.value = t.value.slice(0,ss - 4).concat(t.value.slice(ss,t.value.length));\r\n        t.selectionStart = t.selectionEnd = ss - tab.length;\r\n    }\r\n           \r\n    // Delete key - delete following tab expansion, if exists\r\n    else if (evt.keyCode==46 && t.value.slice(se,se + 4) == tab) {\r\n        evt.preventDefault();\r\n             \r\n        t.value = t.value.slice(0,ss).concat(t.value.slice(ss + 4,t.value.length));\r\n        t.selectionStart = t.selectionEnd = ss;\r\n    }\r\n    // Left/right arrow keys - move across the tab in one go\r\n    else if (evt.keyCode == 37 && t.value.slice(ss - 4,ss) == tab) {\r\n        evt.preventDefault();\r\n        t.selectionStart = t.selectionEnd = ss - 4;\r\n    }\r\n    else if (evt.keyCode == 39 && t.value.slice(ss,ss + 4) == tab) {\r\n        evt.preventDefault();\r\n        t.selectionStart = t.selectionEnd = ss + 4;\r\n    }\r\n}\r\n\r\ndocument.onkeydown=checkTab\r\n 	sys_tabontextarea.js
\.

